name: stackhawk
on: [push]

jobs:
  stackhawk-hawkscan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stackhawk/hawkscan-action@v2.2.0
      with:
        apiKey: ${{ secrets.fossaApiKey }}
